Scikit-Learn Package on Dissertation Datasets
---

In [12]:
import numpy as np
import matplotlib.pyplot as plt
#from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
#from sklearn.preprocessing import StandardScaler
from sklearn import datasets
#from sklearn.datasets import make_moons, make_circles, make_classification
#from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
#from sklearn.gaussian_process import GaussianProcessClassifier
#from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis


from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

**load iris data and put them in $X$ and $y$ variables**

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

**Split the data**

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [14]:
# choose a classifier with relevant parameters

# KNN for example
clf = KNeighborsClassifier(n_neighbors=5)
model = clf.fit(X_train,y_train)
pred_test = clf.predict(X_test)

conf = confusion_matrix(pred_test, y_test)
score = accuracy_score(pred_test, y_test)
print('Confusion Matrix \n',conf)
print('Accuracy \n', score)

Confusion Matrix 
 [[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
Accuracy 
 0.98


Binary-Class Problems
---
**Breast Cancer Dataset**

***Logistic Regression***


In [7]:
import pandas as pd
from sklearn import datasets

cancer = datasets.load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(cancer.data,cancer.target, test_size=0.33, random_state=42)


In [20]:
# Logistic Regression for the cancer sklearn dataset
clf = LogisticRegression()
model = clf.fit(X_train,y_train)
pred_test = clf.predict(X_test)

# 10-fold cross validation
scores = cross_val_score(clf, cancer.data, cancer.target, cv=10)

conf = confusion_matrix(pred_test, y_test)
score = accuracy_score(pred_test, y_test)
print('Confusion Matrix: \n',conf)
print('Accuracy: \n', np.round(score,2))
print('10-Fold Cross Validation accuracies are: \n', np.round(scores,2))
print('Cross Validated Accuracy: \n %0.2f (+/- %0.2f)'% (np.mean(scores), np.std(scores)))

Confusion Matrix: 
 [[ 63   4]
 [  4 117]]
Accuracy: 
 0.96
10-Fold Cross Validation accuracies are: 
 [0.95 0.91 0.93 0.95 0.96 0.98 0.95 0.95 0.96 0.96]
Cross Validated Accuracy: 
 0.95 (+/- 0.02)


**Random Forest**


In [26]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100)
model = clf.fit(X_train, y_train)
pred_test = clf.predict(X_test)

conf = confusion_matrix(pred_test, y_test)
score = accuracy_score(pred_test, y_test)
print('Confusion Matrix: \n',conf)
print('Accuracy: \n', np.round(score,2))


# 10-fold cross validation
scores = cross_val_score(clf, cancer.data, cancer.target, cv=10)
print('10-Fold Cross Validation accuracies are: \n', np.round(scores,2))
print('Cross Validated Accuracy: \n %0.2f (+/- %0.2f)'% (np.mean(scores), np.std(scores)))

Confusion Matrix: 
 [[ 62   3]
 [  5 118]]
Accuracy: 
 0.96
10-Fold Cross Validation accuracies are: 
 [0.98 0.91 0.93 0.96 1.   0.98 0.96 0.98 0.95 1.  ]
Cross Validated Accuracy: 
 0.97 (+/- 0.03)


**Nearest Neighbours**

In [32]:
clf = KNeighborsClassifier(n_neighbors=5)
model = clf.fit(X_train,y_train)
pred_test = clf.predict(X_test)

conf = confusion_matrix(pred_test, y_test)
score = accuracy_score(pred_test, y_test)
print('Confusion Matrix \n',conf)
print('Accuracy \n', score)

# 10-fold cross validation
scores = cross_val_score(clf, cancer.data, cancer.target, cv=10)
print('10-Fold Cross Validation accuracies are: \n', np.round(scores,2))
print('Cross Validated Accuracy: \n %0.2f (+/- %0.2f)'% (np.mean(scores), np.std(scores)))

Confusion Matrix 
 [[ 62   6]
 [  5 115]]
Accuracy 
 0.9414893617021277
10-Fold Cross Validation accuracies are: 
 [0.91 0.86 0.89 0.95 0.95 0.95 0.96 0.95 0.91 0.93]
Cross Validated Accuracy: 
 0.93 (+/- 0.03)


**Naive Bayes**

In [31]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
model = clf.fit(X_train,y_train)
pred_test = clf.predict(X_test)

conf = confusion_matrix(pred_test, y_test)
score = accuracy_score(pred_test, y_test)
print('Confusion Matrix \n',conf)
print('Accuracy \n', score)

# 10-fold cross validation
scores = cross_val_score(clf, cancer.data, cancer.target, cv=10)
print('10-Fold Cross Validation accuracies are: \n', np.round(scores,2))
print('Cross Validated Accuracy: \n %0.2f (+/- %0.2f)'% (np.mean(scores), np.std(scores)))

Confusion Matrix 
 [[ 61   5]
 [  6 116]]
Accuracy 
 0.9414893617021277
10-Fold Cross Validation accuracies are: 
 [0.95 0.88 0.89 0.93 0.95 0.98 0.93 0.96 0.95 0.96]
Cross Validated Accuracy: 
 0.94 (+/- 0.03)


In [34]:
# linear scaling for KNN [0 1]
# LSVT Dataset
# Parkinson's 

         0      1       2       3        4        5         6         7   \
0    17.990  10.38  122.80  1001.0  0.11840  0.27760  0.300100  0.147100   
1    20.570  17.77  132.90  1326.0  0.08474  0.07864  0.086900  0.070170   
2    19.690  21.25  130.00  1203.0  0.10960  0.15990  0.197400  0.127900   
3    11.420  20.38   77.58   386.1  0.14250  0.28390  0.241400  0.105200   
4    20.290  14.34  135.10  1297.0  0.10030  0.13280  0.198000  0.104300   
5    12.450  15.70   82.57   477.1  0.12780  0.17000  0.157800  0.080890   
6    18.250  19.98  119.60  1040.0  0.09463  0.10900  0.112700  0.074000   
7    13.710  20.83   90.20   577.9  0.11890  0.16450  0.093660  0.059850   
8    13.000  21.82   87.50   519.8  0.12730  0.19320  0.185900  0.093530   
9    12.460  24.04   83.97   475.9  0.11860  0.23960  0.227300  0.085430   
10   16.020  23.24  102.70   797.8  0.08206  0.06669  0.032990  0.033230   
11   15.780  17.89  103.60   781.0  0.09710  0.12920  0.099540  0.066060   
12   19.170 

         0      1       2       3        4        5         6         7   \
0    15.460  11.89  102.50   736.9  0.12570  0.15550  0.203200  0.109700   
1    12.850  21.37   82.63   514.5  0.07551  0.08316  0.061260  0.018670   
2    19.210  18.57  125.50  1152.0  0.10530  0.12670  0.132300  0.089940   
3    12.470  17.31   80.45   480.1  0.08928  0.07630  0.036090  0.023690   
4    12.460  19.89   80.43   471.3  0.08451  0.10140  0.068300  0.030990   
5    10.860  21.48   68.51   360.5  0.07431  0.04227  0.000000  0.000000   
6    11.370  18.89   72.17   396.0  0.08713  0.05008  0.023990  0.021730   
7    18.810  19.98  120.90  1102.0  0.08923  0.05884  0.080200  0.058430   
8    13.490  22.30   86.91   561.0  0.08752  0.07698  0.047510  0.033840   
9     9.567  15.91   60.21   279.6  0.08464  0.04087  0.016520  0.016670   
10   17.140  16.40  116.00   912.7  0.11860  0.22760  0.222900  0.140100   
11   11.060  14.83   70.31   378.2  0.07741  0.04768  0.027120  0.007246   
12   14.610 